import { inngest } from "@/inngest/client";
import { db } from "@/lib/db";
import { publishToGithub } from "@/lib/publish/github";

function slugify(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

export const publishDraft = inngest.createFunction(
  {
    id: "publish-draft",
    triggers: [{ event: "draft/publish.requested" }],
    retries: 1,
  },
  async ({ event, step }) => {
    const { draftId } = event.data as { draftId: string };

    const draft = await step.run("load", async () => {
      const d = await db.contentDraft.findUnique({
        where: { id: draftId },
        include: {
          workspace: {
            select: { githubOwner: true, githubRepo: true, githubPath: true },
          },
          opportunity: { select: { title: true, reasoning: true } },
        },
      });
      if (!d) throw new Error("Draft not found");
      if (!d.workspace.githubOwner || !d.workspace.githubRepo) {
        throw new Error("No GitHub repo configured for this workspace");
      }
      return d;
    });

    const slug = slugify(draft.title);
    const branch = "aifdm/" + slug + "-" + Date.now();

    const result = await step.run("publish", async () => {
      return publishToGithub({
        owner: draft.workspace.githubOwner as string,
        repo: draft.workspace.githubRepo as string,
        path: draft.workspace.githubPath ?? "content",
        branch,
        filename: slug + ".md",
        content: "# " + draft.title + "\n\n" + draft.body,
        title: draft.title,
        bodyText:
          "Generated by AIFDM.\n\n**Opportunity:** " +
          draft.opportunity.title +
          "\n\n**Why:** " +
          draft.opportunity.reasoning +
          "\n\n**Rubric score:** " +
          (draft.score === null ? "unscored" : Math.round(draft.score * 100) + "%"),
      });
    });

    await step.run("save", async () => {
      await db.contentDraft.update({
        where: { id: draftId },
        data: {
          status: "PUBLISHED",
          prUrl: result.prUrl,
          publishedAt: new Date(),
        },
      });
    });

    return { prUrl: result.prUrl };
  }
);